include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - annotate_overrides
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_print
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - collection_methods_unrelated_type
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - depend_on_referenced_packages
    - directives_ordering
    - flutter_style_todos
    - null_check_on_nullable_type_parameter
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_void_to_null
    - require_trailing_commas
    - sized_box_for_whitespace
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - use_build_context_synchronously
    - use_decorated_box
    - use_key_in_widget_constructors
    - use_named_constants
    - void_checks

dart_code_metrics:
  rules:
    - avoid-non-null-assertion
    - avoid-unnecessary-setstate
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions:
        severity: error
    - avoid-unused-parameters
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-const-border-radius
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last

  rules-exclude:
    - "**/*.gr.dart"
    - "**/generated_plugin_registrant.dart"

analyzer:
  exclude:
    - "**/*.mocks.dart"
    - "**/*.gr.dart"
    - "test/generated/**"
    - "lib/gen/**"
    - "lib/di.config.dart"

  errors:
    always_use_package_imports: ignore
    avoid_relative_lib_imports: ignore
    deprecated_member_use_from_same_package: ignore
