name: eth_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  xmtp: ^1.2.0
  walletconnect_modal_flutter: ^2.1.6
  walletconnect_flutter_v2: ^2.1.4
  freezed_annotation: ^2.4.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  eth_sig_util: ^0.0.9
  nested: ^1.0.0
  provider: ^6.0.5
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.16
  path_provider: ^2.1.1
  path: ^1.8.3
  fast_immutable_collections: ^9.1.5
  dfunc: ^0.9.0
  injectable: ^2.3.0
  rxdart: ^0.27.7
  bloc_concurrency: ^0.2.2
  get_it: ^7.6.0
  auto_route: ^7.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  auto_route_generator: ^7.3.1
  injectable_generator: ^2.4.0
  drift_dev: ^2.11.1

flutter:
  uses-material-design: true
