name: eth_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  chat_bubbles: ^1.5.0
  cupertino_icons: ^1.0.2
  dfunc: ^0.9.0
  drift: ^2.11.1
  eth_sig_util: ^0.0.9
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  injectable: ^2.3.0
  intl: ^0.18.1
  nested: ^1.0.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  quiver: ^3.2.1
  retry: ^3.1.2
  rxdart: ^0.27.7
  sqlite3_flutter_libs: ^0.5.16
  url_launcher: ^6.1.14
  uuid: ^3.0.7
  walletconnect_flutter_v2: ^2.1.4
  walletconnect_modal_flutter: ^2.1.6
  web3dart: ^2.6.1
  xmtp: ^1.2.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  drift_dev: ^2.11.1
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.4.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
